version: "3"

services:
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - $PWD/influxdb/data:/var/lib/influxdb2
      - $PWD/influxdb/config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: user
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: org
      DOCKER_INFLUXDB_INIT_BUCKET: sample
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: token

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - /tmp/grafana:/var/lib/grafana